version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  node-test:
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app
    command: npm test

networks:
  app-network:
    driver: bridge
